### ISSUE TITLE
Support for Gradle Enterprise 2023.4

### ISSUE THREAD

**Issue by ymengesha** [gabrielfeo/gradle-enterprise-api-kotlin#149]
Hi,

I recently saw your [talk](https://dpesummit.com/sessions/gabriel-feo/unlocking-build-analytics-ifoods-journey-with-the-gradle-enterprise-api/) about using the Gradle Enterprise (Develocity) API to extract interesting metrics. I noticed that the library doesn't yet support some of the endpoints that were mentioned in your talk, specifically the ones regarding flaky tests. As those endpoints are out of beta now, I was wondering if you had any plans to add support for [Gradle 2023.4](https://docs.gradle.com/enterprise/api-manual/ref/2023.4.html).

Cheers!

**Comment by gabrielfeo** [comment]
Hi, @ymengesha! Thank you for your interest in the library!

I haven't released the 2023.4 library yet because I don't have a 2023.4 Develocity instance to fully test it with. Until I do, I published [**2023.4.0-alpha01**](https://github.com/gabrielfeo/gradle-enterprise-api-kotlin/releases/tag/2023.4.0-alpha01) for you to use. It contains the [`TestsApi`](https://gabrielfeo.github.io/gradle-enterprise-api-kotlin/library/com.gabrielfeo.gradle.enterprise.api/-tests-api/index.html). Please report any issues you have and I'll be glad to  help.

**Comment by gabrielfeo** [comment]
I just published [**2023.4.0-alpha03**](https://github.com/gabrielfeo/gradle-enterprise-api-kotlin/releases/tag/2023.4.0-alpha03) and it's stable and tested. I intend to release 2023.4.0 soon.

**Comment by gabrielfeo** [comment]
I've just published [**2023.4.0**](https://github.com/gabrielfeo/gradle-enterprise-api-kotlin/releases/tag/2023.4.0). Sorry about the delay! Let me know if you have any issues or suggestions.
